package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name="alumnos"
    ,catalog="dbcolegio2"
)
public class Alumnos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idAlumno;
     private String nombres;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String dni;
     private char sexo;
     private Date fechaNacimiento;
     private String nombrePadre;
     private String nombreMadre;
     private String nombreApoderado;
     private String telefono;
     private String celular;
     private String direccion;
     private String distrito;
     private char estado;
     private String codigoColegio;
     private Set<Matriculas> matriculases = new HashSet<Matriculas>(0);

    public Alumnos() {
    }

	
    public Alumnos(String nombres, String apellidos, String dni, char sexo, Date fechaNacimiento, String nombrePadre, String nombreMadre, String nombreApoderado, String direccion, String distrito, char estado, String codigoColegio) {
        this.nombres = nombres;
        
        this.dni = dni;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.nombrePadre = nombrePadre;
        this.nombreMadre = nombreMadre;
        this.nombreApoderado = nombreApoderado;
        this.direccion = direccion;
        this.distrito = distrito;
        this.estado = estado;
        this.codigoColegio = codigoColegio;
    }
    public Alumnos(String nombres, String apellidos, String dni, char sexo, Date fechaNacimiento, String nombrePadre, String nombreMadre, String nombreApoderado, String telefono, String celular, String direccion, String distrito, char estado, String codigoColegio, Set<Matriculas> matriculases) {
       this.nombres = nombres;
       
       this.dni = dni;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.nombrePadre = nombrePadre;
       this.nombreMadre = nombreMadre;
       this.nombreApoderado = nombreApoderado;
       this.telefono = telefono;
       this.celular = celular;
       this.direccion = direccion;
       this.distrito = distrito;
       this.estado = estado;
       this.codigoColegio = codigoColegio;
       this.matriculases = matriculases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdAlumno", unique=true, nullable=false)
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }

    
    @Column(name="Nombres", nullable=false, length=70)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    


    
    @Column(name="Dni", nullable=false, length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="Sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)    
    @Column(name="FechaNacimiento", nullable=true)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="NombrePadre", nullable=false, length=150)
    public String getNombrePadre() {
        return this.nombrePadre;
    }
    
    public void setNombrePadre(String nombrePadre) {
        this.nombrePadre = nombrePadre;
    }
    @Column(name="ApellidoPaterno", nullable=false, length=50)
    public String getApellidoPaterno() {
		return apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name="ApellidoMaterno", nullable=false, length=50)
	public String getApellidoMaterno() {
		return apellidoMaterno;
	}


	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}


	@Column(name="NombreMadre", nullable=false, length=150)
    public String getNombreMadre() {
        return this.nombreMadre;
    }
    
    public void setNombreMadre(String nombreMadre) {
        this.nombreMadre = nombreMadre;
    }

    
    @Column(name="NombreApoderado", nullable=false, length=150)
    public String getNombreApoderado() {
        return this.nombreApoderado;
    }
    
    public void setNombreApoderado(String nombreApoderado) {
        this.nombreApoderado = nombreApoderado;
    }

    
    @Column(name="Telefono", length=11)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Celular", length=9)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="Direccion", nullable=false, length=180)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Distrito", nullable=false, length=90)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alumnos")
    public Set<Matriculas> getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set<Matriculas> matriculases) {
        this.matriculases = matriculases;
    }


}


