package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name="alumnos"
    ,catalog="dbcolegio2"
)
public class Alumnos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Short idAlumno;
     private String nombres;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String dni;
     private Date fechaNacimiento;
     private String edad;
     private char sexo;
     private String direccion;
     private String distrito;
     private String responsable;
     private String religion;
     private byte[] foto;
     private String estado;
     private String nombrePadre;
     private String apellidosPadre;
     private String dniPadre;
     private Date fechaNacPadre;
     private String estadoCivilPadre;
     private String telefonoPadre;
     private String celularPadre;
     private String direccionPadre;
     private String distritoPadre;
     private String ocupacionPadre;
     private String religionPadre;
     private String estaVivoPadre;
     private String nombreMadre;
     private String apellidosMadre;
     private String dniMadre;
     private Date fechaNacMadre;
     private String estadoCivilMadre;
     private String telefonoMadre;
     private String celularMadre;
     private String direccionMadre;
     private String distritoMadre;
     private String ocupacionMadre;
     private String religionMadre;
     private String estaVivoMadre;
     private String nombreApoderado;
     private String apellidosApoderado;
     private String dniApoderado;
     private Date fechaNacApoderado;
     private String estadoCivilApoderado;
     private String telefonoApoderado;
     private String celularApoderado;
     private String direccionApoderado;
     private String distritoApoderado;
     private String ocupacionApoderado;
     private String religionApoderado;
     private String estaVivoApoderado;
     private String nombreCompleto;
     private String codigoColegio;
     

    public Alumnos() {
    }
    
     
    public Alumnos(Short idAlumno) {
		super();
		this.idAlumno = idAlumno;
	}



	public Alumnos( String nombres, String apellidoPaterno,
			String apellidoMaterno, String dni, Date fechaNacimiento,
			String edad, char sexo, String direccion, String distrito,
			String responsable, String religion, byte[] foto,String nombrePadre,
			String apellidosPadre, String dniPadre, Date fechaNacPadre,
			String estadoCivilPadre, String telefonoPadre, String celularPadre,
			String direccionPadre, String distritoPadre, String ocupacionPadre,
			String religionPadre, String estaVivoPadre,String nombreMadre,
			String apellidosMadre, String dniMadre, Date fechaNacMadre,
			String estadoCivilMadre, String telefonoMadre, String celularMadre,
			String direccionMadre, String distritoMadre, String ocupacionMadre,String religionMadre,String estaVivoMadre,String nombreApoderado,
			String apellidosApoderado, String dniApoderado,
			Date fechaNacApoderado, String estadoCivilApoderado,
			String telefonoApoderado, String celularApoderado,
			String direccionApoderado, String distritoApoderado,
			String ocupacionApoderado,String estado, String religionApoderado,String estaVivoApoderado,String nombreCompleto,String codigoColegio) {
		super();
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.dni = dni;
		this.fechaNacimiento = fechaNacimiento;
		this.edad = edad;
		this.sexo = sexo;
		this.direccion = direccion;
		this.distrito = distrito;
		this.responsable = responsable;
		this.religion = religion;
		this.foto = foto;
		this.nombrePadre = nombrePadre;
		this.apellidosPadre = apellidosPadre;
		this.dniPadre = dniPadre;
		this.fechaNacPadre = fechaNacPadre;
		this.estadoCivilPadre = estadoCivilPadre;
		this.telefonoPadre = telefonoPadre;
		this.celularPadre = celularPadre;
		this.direccionPadre = direccionPadre;
		this.distritoPadre = distritoPadre;
		this.ocupacionPadre = ocupacionPadre;
		this.religionPadre = religionPadre;
		this.estaVivoPadre = estaVivoPadre;

		this.nombreMadre = nombreMadre;
		this.apellidosMadre = apellidosMadre;
		this.dniMadre = dniMadre;
		this.fechaNacMadre = fechaNacMadre;
		this.estadoCivilMadre = estadoCivilMadre;
		this.telefonoMadre = telefonoMadre;
		this.celularMadre = celularMadre;
		this.direccionMadre = direccionMadre;
		this.distritoMadre = distritoMadre;
		this.ocupacionMadre = ocupacionMadre;
		this.religionMadre=religionMadre;
		this.estaVivoMadre=estaVivoMadre;
		this.nombreApoderado = nombreApoderado;
		this.apellidosApoderado = apellidosApoderado;
		this.dniApoderado = dniApoderado;
		this.fechaNacApoderado = fechaNacApoderado;
		this.estadoCivilApoderado = estadoCivilApoderado;
		this.telefonoApoderado = telefonoApoderado;
		this.celularApoderado = celularApoderado;
		this.direccionApoderado = direccionApoderado;
		this.distritoApoderado = distritoApoderado;
		this.ocupacionApoderado = ocupacionApoderado;
		this.religionApoderado = religionApoderado;
		this.estaVivoApoderado = estaVivoApoderado;
		this.nombreCompleto=nombreCompleto;
		this.estado = estado;
		this.codigoColegio=codigoColegio;
			}


	
	public Alumnos( String nombres, String apellidoPaterno,
			String apellidoMaterno, String dni, Date fechaNacimiento,
			String edad, char sexo, String direccion, String distrito,
			String responsable, String religion, byte[] foto) {
		super();
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.dni = dni;
		this.fechaNacimiento = fechaNacimiento;
		this.edad = edad;
		this.sexo = sexo;
		this.direccion = direccion;
		this.distrito = distrito;
		this.responsable = responsable;
		this.religion = religion;
		this.foto = foto;		
	
	}


	@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="IdAlumno", unique=true, nullable=false, length = 8)
    public Short getIdAlumno() {
		return idAlumno;
	}


	public void setIdAlumno(Short idAlumno) {
		this.idAlumno = idAlumno;
	}

	@Column(name = "Nombres", nullable = false, length = 70)
	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "ApellidoPaterno", nullable = false, length = 50)
	public String getApellidoPaterno() {
		return apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "ApellidoMaterno", nullable = false, length = 50)
	public String getApellidoMaterno() {
		return apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "DNI", nullable = false, length = 8)
	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacimiento", nullable = false, length = 30)
	public Date getFechaNacimiento() {
		return fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "Edad", nullable = false, length = 2)
	public String getEdad() {
		return edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	@Column(name = "Sexo", nullable = false, length = 1)
	public char getSexo() {
		return sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Direccion", nullable = false, length = 180)
	public String getDireccion() {
		return direccion;
	}


	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Distrito", nullable = false, length = 90)
	public String getDistrito() {
		return distrito;
	}


	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "Responsable", nullable = false, length = 10)
	public String getResponsable() {
		return responsable;
	}


	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@Column(name = "Religion", nullable = false, length = 20)
	public String getReligion() {
		return religion;
	}


	public void setReligion(String religion) {
		this.religion = religion;
	}

	 @Column(name="Foto")
	public byte[] getFoto() {
		return foto;
	}


	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	
	@Column(name = "NombrePadre", nullable = false, length = 150)
	public String getNombrePadre() {
		return nombrePadre;
	}


	public void setNombrePadre(String nombrePadre) {
		this.nombrePadre = nombrePadre;
	}


	@Column(name = "ApellidosPadre", nullable = false, length = 150)
	public String getApellidosPadre() {
		return apellidosPadre;
	}


	public void setApellidosPadre(String apellidosPadre) {
		this.apellidosPadre = apellidosPadre;
	}

	@Column(name = "DNIPadre", nullable = false, length = 8)
	public String getDniPadre() {
		return dniPadre;
	}


	public void setDniPadre(String dniPadre) {
		this.dniPadre = dniPadre;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacPadre", nullable = false, length = 30)
	public Date getFechaNacPadre() {
		return fechaNacPadre;
	}


	public void setFechaNacPadre(Date fechaNacPadre) {
		this.fechaNacPadre = fechaNacPadre;
	}

	@Column(name = "EstadoCivilPadre", nullable = false, length = 20)
	public String getEstadoCivilPadre() {
		return estadoCivilPadre;
	}


	public void setEstadoCivilPadre(String estadoCivilPadre) {
		this.estadoCivilPadre = estadoCivilPadre;
	}

	@Column(name = "TelefonoPadre", nullable = false, length = 10)
	public String getTelefonoPadre() {
		return telefonoPadre;
	}

	
	public void setTelefonoPadre(String telefonoPadre) {
		this.telefonoPadre = telefonoPadre;
	}

	@Column(name = "CelularPadre", nullable = false, length = 9)
	public String getCelularPadre() {
		return celularPadre;
	}


	public void setCelularPadre(String celularPadre) {
		this.celularPadre = celularPadre;
	}

	@Column(name = "DireccionPadre", nullable = false, length = 180)
	public String getDireccionPadre() {
		return direccionPadre;
	}


	public void setDireccionPadre(String direccionPadre) {
		this.direccionPadre = direccionPadre;
	}

	@Column(name = "DistritoPadre", nullable = false, length = 90)
	public String getDistritoPadre() {
		return distritoPadre;
	}


	public void setDistritoPadre(String distritoPadre) {
		this.distritoPadre = distritoPadre;
	}

	@Column(name = "OcupacionPadre", nullable = false, length = 100)
	public String getOcupacionPadre() {
		return ocupacionPadre;
	}


	public void setOcupacionPadre(String ocupacionPadre) {
		this.ocupacionPadre = ocupacionPadre;
	}

	@Column(name = "ReligionPadre", nullable = false, length = 20)
	public String getReligionPadre() {
		return religionPadre;
	}


	public void setReligionPadre(String religionPadre) {
		this.religionPadre = religionPadre;
	}

	@Column(name = "EstaVivoPadre", nullable = false, length = 2)
	public String getEstaVivoPadre() {
		return estaVivoPadre;
	}


	public void setEstaVivoPadre(String estaVivoPadre) {
		this.estaVivoPadre = estaVivoPadre;
	}

	@Column(name = "NombreMadre", nullable = false, length = 150)
	public String getNombreMadre() {
		return nombreMadre;
	}


	public void setNombreMadre(String nombreMadre) {
		this.nombreMadre = nombreMadre;
	}

	@Column(name = "ApellidosMadre", nullable = false, length = 150)
	public String getApellidosMadre() {
		return apellidosMadre;
	}


	public void setApellidosMadre(String apellidosMadre) {
		this.apellidosMadre = apellidosMadre;
	}

	@Column(name = "DNIMadre", nullable = false, length = 8)
	public String getDniMadre() {
		return dniMadre;
	}


	public void setDniMadre(String dniMadre) {
		this.dniMadre = dniMadre;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacMadre", nullable = false, length = 30)
	public Date getFechaNacMadre() {
		return fechaNacMadre;
	}


	public void setFechaNacMadre(Date fechaNacMadre) {
		this.fechaNacMadre = fechaNacMadre;
	}


	@Column(name = "EstadoCivilMadre", nullable = false, length = 20)
	public String getEstadoCivilMadre() {
		return estadoCivilMadre;
	}


	public void setEstadoCivilMadre(String estadoCivilMadre) {
		this.estadoCivilMadre = estadoCivilMadre;
	}

	@Column(name = "TelefonoMadre", nullable = false, length = 10)
	public String getTelefonoMadre() {
		return telefonoMadre;
	}


	public void setTelefonoMadre(String telefonoMadre) {
		this.telefonoMadre = telefonoMadre;
	}

	@Column(name = "CelularMadre", nullable = false, length = 9)
	public String getCelularMadre() {
		return celularMadre;
	}


	public void setCelularMadre(String celularMadre) {
		this.celularMadre = celularMadre;
	}

	@Column(name = "DireccionMadre", nullable = false, length = 180)
	public String getDireccionMadre() {
		return direccionMadre;
	}


	public void setDireccionMadre(String direccionMadre) {
		this.direccionMadre = direccionMadre;
	}

	@Column(name = "DistritoMadre", nullable = false, length = 90)
	public String getDistritoMadre() {
		return distritoMadre;
	}


	public void setDistritoMadre(String distritoMadre) {
		this.distritoMadre = distritoMadre;
	}

	@Column(name = "OcupacionMadre", nullable = false, length = 100)
	public String getOcupacionMadre() {
		return ocupacionMadre;
	}


	public void setOcupacionMadre(String ocupacionMadre) {
		this.ocupacionMadre = ocupacionMadre;
	}

	@Column(name = "ReligionMadre", nullable = false, length = 20)	
public String getReligionMadre() {
		return religionMadre;
	}


	public void setReligionMadre(String religionMadre) {
		this.religionMadre = religionMadre;
	}

	@Column(name = "EstaVivoMadre", nullable = false, length = 2)
	public String getEstaVivoMadre() {
		return estaVivoMadre;
	}


	public void setEstaVivoMadre(String estaVivoMadre) {
		this.estaVivoMadre = estaVivoMadre;
	}

	@Column(name = "NombreApoderado", nullable = false, length = 150)
	public String getNombreApoderado() {
		return nombreApoderado;
	}


	public void setNombreApoderado(String nombreApoderado) {
		this.nombreApoderado = nombreApoderado;
	}


	@Column(name = "ApellidosApoderado", nullable = false, length = 150)
	public String getApellidosApoderado() {
		return apellidosApoderado;
	}


	public void setApellidosApoderado(String apellidosApoderado) {
		this.apellidosApoderado = apellidosApoderado;
	}

	@Column(name = "DNIApoderado", nullable = false, length = 8)
	public String getDniApoderado() {
		return dniApoderado;
	}


	public void setDniApoderado(String dniApoderado) {
		this.dniApoderado = dniApoderado;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "FechaNacApoderado", nullable = false, length = 30)
	public Date getFechaNacApoderado() {
		return fechaNacApoderado;
	}


	public void setFechaNacApoderado(Date fechaNacApoderado) {
		this.fechaNacApoderado = fechaNacApoderado;
	}

	@Column(name = "EstadoCivilApoderado", nullable = false, length = 20)
	public String getEstadoCivilApoderado() {
		return estadoCivilApoderado;
	}


	public void setEstadoCivilApoderado(String estadoCivilApoderado) {
		this.estadoCivilApoderado = estadoCivilApoderado;
	}

	@Column(name = "TelefonoApoderado", nullable = false, length = 10)
	public String getTelefonoApoderado() {
		return telefonoApoderado;
	}


	public void setTelefonoApoderado(String telefonoApoderado) {
		this.telefonoApoderado = telefonoApoderado;
	}

	@Column(name = "CelularApoderado", nullable = false, length = 9)
	public String getCelularApoderado() {
		return celularApoderado;
	}


	public void setCelularApoderado(String celularApoderado) {
		this.celularApoderado = celularApoderado;
	}

	@Column(name = "DireccionApoderado", nullable = false, length = 180)
	public String getDireccionApoderado() {
		return direccionApoderado;
	}


	public void setDireccionApoderado(String direccionApoderado) {
		this.direccionApoderado = direccionApoderado;
	}

	@Column(name = "DistritoApoderado", nullable = false, length = 90)
	public String getDistritoApoderado() {
		return distritoApoderado;
	}


	public void setDistritoApoderado(String distritoApoderado) {
		this.distritoApoderado = distritoApoderado;
	}

	@Column(name = "OcupacionApoderado", nullable = false, length = 100)
	public String getOcupacionApoderado() {
		return ocupacionApoderado;
	}


	public void setOcupacionApoderado(String ocupacionApoderado) {
		this.ocupacionApoderado = ocupacionApoderado;
	}

	@Column(name = "ReligionApoderado", nullable = false, length = 20)
	public String getReligionApoderado() {
		return religionApoderado;
	}


	public void setReligionApoderado(String religionApoderado) {
		this.religionApoderado = religionApoderado;
	}

	@Column(name = "EstaVivoApoderado", nullable = false, length = 2)
	public String getEstaVivoApoderado() {
		return estaVivoApoderado;
	}


	public void setEstaVivoApoderado(String estaVivoApoderado) {
		this.estaVivoApoderado = estaVivoApoderado;
	}


	
	
	

	@Column(name = "nombreCompleto", nullable = false, length = 100)
	public String getNombreCompleto() {
		return nombreCompleto;
	}


	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	  @Column(name="estado", nullable=false, length=10)
	    public String getEstado() {
	        return this.estado;
	    }
	    
	    public void setEstado(String estado) {
	        this.estado = estado;
	    }

	    @Column(name="codigoColegio", nullable=false, length=11)
		public String getCodigoColegio() {
			return codigoColegio;
		}

		  public void setCodigoColegio(String codigoColegio) {
			this.codigoColegio = codigoColegio;
		}

	    


}




