package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name="alumnos"
    ,catalog="dbcolegio2"
)
public class Alumnos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
//	private Integer idAlumno;
	private String idAlumno;
     private String nombres;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String dni;
     private char sexo;
     private Date fechaNacimiento;
     private String telefono;
     private String celular;
     private String direccion;
     private String distrito;
     private char estado;
     private String codigoColegio;
     
     private String edad;
     private String responsable;
     private String religion;
     private String nombrePadre;
     private String apellidosPadre;
     private String dniPadre;
     private Date fechaNacPadre;
     private String estadoCivilPadre;
     private String telefonoPadre;
     private String celularPadre;
     private String direccionPadre;
     private String distritoPadre;
     private String ocupacionPadre;
     private String religionPadre;
     private String estaVivoPadre;
     private String nombreMadre;
     private String apellidosMadre;
     private String dniMadre;
     private Date fechaNacMadre;
     private String estadoCivilMadre;
     private String telefonoMadre;
     private String celularMadre;
     private String direccionMadre;
     private String distritoMadre;
     private String ocupacionMadre;
     private String religionMadre;
     private String estaVivoMadre;
     private String nombreApoderado;
     private String apellidosApoderado;
     private String dniApoderado;
     private Date fechaNacApoderado;
     private String estadoCivilApoderado;
     private String telefonoApoderado;
     private String celularApoderado;
     private String direccionApoderado;
     private String distritoApoderado;
     private String ocupacionApoderado;
     private String religionApoderado;
     private String estaVivoApoderado;
     
     
     private Set<Matriculas> matriculases = new HashSet<Matriculas>(0);

    public Alumnos() {
    }

	
    public Alumnos(String nombres, String apellidos, String dni, char sexo, Date fechaNacimiento, String nombrePadre, String nombreMadre, String nombreApoderado, String direccion, String distrito, char estado, String codigoColegio) {
        this.nombres = nombres;
        
        this.dni = dni;
        this.sexo = sexo;
        this.fechaNacimiento = fechaNacimiento;
        this.nombrePadre = nombrePadre;
        this.nombreMadre = nombreMadre;
        this.nombreApoderado = nombreApoderado;
        this.direccion = direccion;
        this.distrito = distrito;
        this.estado = estado;
        this.codigoColegio = codigoColegio;
    }
    public Alumnos(String nombres, String apellidos, String dni, char sexo, Date fechaNacimiento, String nombrePadre, String nombreMadre, String nombreApoderado, String telefono, String celular, String direccion, String distrito, char estado, String codigoColegio, Set<Matriculas> matriculases) {
       this.nombres = nombres;
       
       this.dni = dni;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.nombrePadre = nombrePadre;
       this.nombreMadre = nombreMadre;
       this.nombreApoderado = nombreApoderado;
       this.telefono = telefono;
       this.celular = celular;
       this.direccion = direccion;
       this.distrito = distrito;
       this.estado = estado;
       this.codigoColegio = codigoColegio;
       this.matriculases = matriculases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdAlumno", unique=true, nullable=false)
     
     public String getIdAlumno() {
 		return idAlumno;
 	}


 	public void setIdAlumno(String idAlumno) {
 		this.idAlumno = idAlumno;
 	}
//    public Integer getIdAlumno() {
//        return this.idAlumno;
//    }
//    
//    public void setIdAlumno(Integer idAlumno) {
//        this.idAlumno = idAlumno;
//    }

    
    @Column(name="Nombres", nullable=false, length=70)
    public String getNombres() {
        return this.nombres;
    }



	public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    


    
    @Column(name="Dni", nullable=false, length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="Sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)    
    @Column(name="FechaNacimiento", nullable=true)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="NombrePadre", nullable=false, length=150)
    public String getNombrePadre() {
        return this.nombrePadre;
    }
    
    public void setNombrePadre(String nombrePadre) {
        this.nombrePadre = nombrePadre;
    }
    @Column(name="ApellidoPaterno", nullable=false, length=50)
    public String getApellidoPaterno() {
		return apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name="ApellidoMaterno", nullable=false, length=50)
	public String getApellidoMaterno() {
		return apellidoMaterno;
	}


	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}


	@Column(name="NombreMadre", nullable=false, length=150)
    public String getNombreMadre() {
        return this.nombreMadre;
    }
    
    public void setNombreMadre(String nombreMadre) {
        this.nombreMadre = nombreMadre;
    }

    
    @Column(name="NombreApoderado", nullable=false, length=150)
    public String getNombreApoderado() {
        return this.nombreApoderado;
    }
    
    public void setNombreApoderado(String nombreApoderado) {
        this.nombreApoderado = nombreApoderado;
    }

    
    @Column(name="Telefono", length=11)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Celular", length=9)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="Direccion", nullable=false, length=180)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Distrito", nullable=false, length=90)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }
    
    

public String getEdad() {
		return edad;
	}


	public void setEdad(String edad) {
		this.edad = edad;
	}


	public String getResponsable() {
		return responsable;
	}


	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}


	public String getReligion() {
		return religion;
	}


	public void setReligion(String religion) {
		this.religion = religion;
	}


	public String getApellidosPadre() {
		return apellidosPadre;
	}


	public void setApellidosPadre(String apellidosPadre) {
		this.apellidosPadre = apellidosPadre;
	}


	public String getDniPadre() {
		return dniPadre;
	}


	public void setDniPadre(String dniPadre) {
		this.dniPadre = dniPadre;
	}


	public Date getFechaNacPadre() {
		return fechaNacPadre;
	}


	public void setFechaNacPadre(Date fechaNacPadre) {
		this.fechaNacPadre = fechaNacPadre;
	}


	public String getEstadoCivilPadre() {
		return estadoCivilPadre;
	}


	public void setEstadoCivilPadre(String estadoCivilPadre) {
		this.estadoCivilPadre = estadoCivilPadre;
	}


	public String getTelefonoPadre() {
		return telefonoPadre;
	}


	public void setTelefonoPadre(String telefonoPadre) {
		this.telefonoPadre = telefonoPadre;
	}


	public String getCelularPadre() {
		return celularPadre;
	}


	public void setCelularPadre(String celularPadre) {
		this.celularPadre = celularPadre;
	}


	public String getDireccionPadre() {
		return direccionPadre;
	}


	public void setDireccionPadre(String direccionPadre) {
		this.direccionPadre = direccionPadre;
	}


	public String getDistritoPadre() {
		return distritoPadre;
	}


	public void setDistritoPadre(String distritoPadre) {
		this.distritoPadre = distritoPadre;
	}


	public String getOcupacionPadre() {
		return ocupacionPadre;
	}


	public void setOcupacionPadre(String ocupacionPadre) {
		this.ocupacionPadre = ocupacionPadre;
	}


	public String getReligionPadre() {
		return religionPadre;
	}


	public void setReligionPadre(String religionPadre) {
		this.religionPadre = religionPadre;
	}


	public String getEstaVivoPadre() {
		return estaVivoPadre;
	}


	public void setEstaVivoPadre(String estaVivoPadre) {
		this.estaVivoPadre = estaVivoPadre;
	}


	public String getApellidosMadre() {
		return apellidosMadre;
	}


	public void setApellidosMadre(String apellidosMadre) {
		this.apellidosMadre = apellidosMadre;
	}


	public String getDniMadre() {
		return dniMadre;
	}


	public void setDniMadre(String dniMadre) {
		this.dniMadre = dniMadre;
	}


	public Date getFechaNacMadre() {
		return fechaNacMadre;
	}


	public void setFechaNacMadre(Date fechaNacMadre) {
		this.fechaNacMadre = fechaNacMadre;
	}


	public String getEstadoCivilMadre() {
		return estadoCivilMadre;
	}


	public void setEstadoCivilMadre(String estadoCivilMadre) {
		this.estadoCivilMadre = estadoCivilMadre;
	}


	public String getTelefonoMadre() {
		return telefonoMadre;
	}


	public void setTelefonoMadre(String telefonoMadre) {
		this.telefonoMadre = telefonoMadre;
	}


	public String getCelularMadre() {
		return celularMadre;
	}


	public void setCelularMadre(String celularMadre) {
		this.celularMadre = celularMadre;
	}


	public String getDireccionMadre() {
		return direccionMadre;
	}


	public void setDireccionMadre(String direccionMadre) {
		this.direccionMadre = direccionMadre;
	}


	public String getDistritoMadre() {
		return distritoMadre;
	}


	public void setDistritoMadre(String distritoMadre) {
		this.distritoMadre = distritoMadre;
	}


	public String getOcupacionMadre() {
		return ocupacionMadre;
	}


	public void setOcupacionMadre(String ocupacionMadre) {
		this.ocupacionMadre = ocupacionMadre;
	}


	public String getReligionMadre() {
		return religionMadre;
	}


	public void setReligionMadre(String religionMadre) {
		this.religionMadre = religionMadre;
	}


	public String getEstaVivoMadre() {
		return estaVivoMadre;
	}


	public void setEstaVivoMadre(String estaVivoMadre) {
		this.estaVivoMadre = estaVivoMadre;
	}


	public String getApellidosApoderado() {
		return apellidosApoderado;
	}


	public void setApellidosApoderado(String apellidosApoderado) {
		this.apellidosApoderado = apellidosApoderado;
	}


	public String getDniApoderado() {
		return dniApoderado;
	}


	public void setDniApoderado(String dniApoderado) {
		this.dniApoderado = dniApoderado;
	}


	public Date getFechaNacApoderado() {
		return fechaNacApoderado;
	}


	public void setFechaNacApoderado(Date fechaNacApoderado) {
		this.fechaNacApoderado = fechaNacApoderado;
	}


	public String getEstadoCivilApoderado() {
		return estadoCivilApoderado;
	}


	public void setEstadoCivilApoderado(String estadoCivilApoderado) {
		this.estadoCivilApoderado = estadoCivilApoderado;
	}


	public String getTelefonoApoderado() {
		return telefonoApoderado;
	}


	public void setTelefonoApoderado(String telefonoApoderado) {
		this.telefonoApoderado = telefonoApoderado;
	}


	public String getCelularApoderado() {
		return celularApoderado;
	}


	public void setCelularApoderado(String celularApoderado) {
		this.celularApoderado = celularApoderado;
	}


	public String getDireccionApoderado() {
		return direccionApoderado;
	}


	public void setDireccionApoderado(String direccionApoderado) {
		this.direccionApoderado = direccionApoderado;
	}


	public String getDistritoApoderado() {
		return distritoApoderado;
	}


	public void setDistritoApoderado(String distritoApoderado) {
		this.distritoApoderado = distritoApoderado;
	}


	public String getOcupacionApoderado() {
		return ocupacionApoderado;
	}


	public void setOcupacionApoderado(String ocupacionApoderado) {
		this.ocupacionApoderado = ocupacionApoderado;
	}


	public String getReligionApoderado() {
		return religionApoderado;
	}


	public void setReligionApoderado(String religionApoderado) {
		this.religionApoderado = religionApoderado;
	}


	public String getEstaVivoApoderado() {
		return estaVivoApoderado;
	}


	public void setEstaVivoApoderado(String estaVivoApoderado) {
		this.estaVivoApoderado = estaVivoApoderado;
	}


@OneToMany(fetch=FetchType.LAZY, mappedBy="alumnos")
    public Set<Matriculas> getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set<Matriculas> matriculases) {
        this.matriculases = matriculases;
    }


}


