package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colegio generated by hbm2java
 */
@Entity
@Table(name="colegio"
    ,catalog="dbcolegio2"
)
public class Colegio  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codigoColegio;
     private String razonSocial;
     private String correo;
     private String direccion;
     private String telefono;
     private String fax;
     private byte[] logo;

    public Colegio() {
    }

	
    public Colegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }
    public Colegio(String codigoColegio, String razonSocial, String correo, String direccion, String telefono, String fax, byte[] logo) {
       this.codigoColegio = codigoColegio;
       this.razonSocial = razonSocial;
       this.correo = correo;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fax = fax;
       this.logo = logo;
    }
   
     @Id 

    
    @Column(name="CodigoColegio", unique=true, nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }

    
    @Column(name="RazonSocial", length=50)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="Correo", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="Direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Fax", length=20)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="Logo")
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }




}


