package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name="empleados"
    ,catalog="dbcolegio2"
)
public class Empleado  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
//	private Integer idEmpleado;
	private String idEmpleado;
     private String nombres;
     private String apellidos;
     private String dni;
     private char sexo;
     private Date fechaNacimiento;
     private String telefono;
     private String celular;
     private String direccion;
     private String distrito;
     private String cargo;
     private String especialidad;
     private char estado;
     private String nombreCompleto;
     private String codigoColegio;
     private Set<Nivel> nivelsForTutor = new HashSet<Nivel>(0);
     private Set<Nivel> nivelsForCoTutor = new HashSet<Nivel>(0);
     private Set<Horarios> horarioses = new HashSet<Horarios>(0);
//     private Set<Usuario> usuarioses = new HashSet<Usuario>(0);



   
     @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="IdEmpleado", unique=true, nullable=false)
     public String getIdEmpleado() {
 		return idEmpleado;
 	}

 	public void setIdEmpleado(String idEmpleado) {
 		this.idEmpleado = idEmpleado;
 	}
//    public Integer getIdEmpleado() {
//        return this.idEmpleado;
//    }
//    
//    public void setIdEmpleado(Integer idEmpleado) {
//        this.idEmpleado = idEmpleado;
//    }
    
    
    @Column(name="Nombres", nullable=false, length=70)
    public String getNombres() {
        return this.nombres;
    }
    


	public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="Apellidos", nullable=false, length=80)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Dni", nullable=false, length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="Sexo", nullable=false, length=1)
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaNacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="Telefono", length=11)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Celular", length=9)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="Direccion", nullable=false, length=180)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="Distrito", nullable=false, length=90)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="Cargo", nullable=false, length=60)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="Especialidad", length=90)
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleadosByTutor")
    public Set<Nivel> getNivelsForTutor() {
        return this.nivelsForTutor;
    }
    
    public void setNivelsForTutor(Set<Nivel> nivelsForTutor) {
        this.nivelsForTutor = nivelsForTutor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleadosByCoTutor")
    public Set<Nivel> getNivelsForCoTutor() {
        return this.nivelsForCoTutor;
    }
    
    public void setNivelsForCoTutor(Set<Nivel> nivelsForCoTutor) {
        this.nivelsForCoTutor = nivelsForCoTutor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleados")
    public Set<Horarios> getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set<Horarios> horarioses) {
        this.horarioses = horarioses;
    }

    @Column(name="nombreCompleto", length=100)
	public String getNombreCompleto() {
		return nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}
    

//@OneToOne(fetch=FetchType.LAZY, mappedBy="empleados")
//    public Set<Usuario> getUsuarioses() {
//        return this.usuarioses;
//    }
//    
//    public void setUsuarioses(Set<Usuario> usuarioses) {
//        this.usuarioses = usuarioses;
//    }

}


