package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name="empleados"
    ,catalog="dbcolegio2"
)
public class Empleado  implements java.io.Serializable {

	
		private static final long serialVersionUID = 1L;
		private String idEmpleado;
	     private String nombres;
	     private String apellidos;
	     private Date fechaNacimiento;
	     private char sexo;
	     private String direccion;
	     private String distrito;
	     private String celular;
	     private String cargo;
	     private String nombreCompleto;
	     
	  
	  //   private String cargo;
	     
	    public Empleado() {
	    }
	    public Empleado(String idEmpleado) {
	        this.idEmpleado = idEmpleado;
	    }
	    
	    
	   
	     public Empleado(String idEmpleado, String nombreCompleto,String nombres, String apellidos, Date fechaNacimiento, char sexo,String direccion,String distrito,String celular,String cargo) {
			super();
			this.idEmpleado = idEmpleado;
			this.nombres = nombres;
			this.apellidos = apellidos;
			 this.fechaNacimiento = fechaNacimiento;
			 this.sexo=sexo;
			this.direccion=direccion;
			 this.distrito=distrito;
			this.celular=celular;
			 this.cargo=cargo;
			 this.nombreCompleto=nombreCompleto;
		}

	    @Id
	    @Column(name="idEmpleado", unique=true, nullable=false, length=8)
	    public String getIdEmpleado() {
	        return this.idEmpleado;
	    }
	    
	    public void setIdEmpleado(String idEmpleado) {
	        this.idEmpleado = idEmpleado;
	    }

	    
	    
	    @Column(name="nombres", nullable=false, length=70)
	    public String getNombres() {
	        return this.nombres;
	    }
	    
	    public void setNombres(String nombres) {
	        this.nombres = nombres;
	    }

	    
	    @Column(name="apellidos", nullable=false, length=80)
	    public String getApellidos() {
	        return this.apellidos;
	    }
	    
	    public void setApellidos(String apellidos) {
	        this.apellidos = apellidos;
	    }
	    @Temporal(TemporalType.DATE)
	    @Column(name="fechaNacimiento", nullable=false, length=30)
	    public Date getFechaNacimiento() {
	    	
	        return this.fechaNacimiento;
	    }
	    
	    public void setFechaNacimiento(Date fechaNacimiento) {
	        this.fechaNacimiento = fechaNacimiento;
	    }
	    
	    @Column(name="sexo", nullable=false, length=1)
	    public char getSexo() {
	        return this.sexo;
	    }
	    
	    public void setSexo(char sexo) {
	        this.sexo = sexo;
	    }
	    
	   @Column(name="direccion", nullable=false, length=180)
	   public String getDireccion() {        return this.direccion;    }
	    
	    public void setDireccion(String direccion) {        this.direccion = direccion;    }

	    
	   @Column(name="distrito", nullable=false, length=90)
	    public String getDistrito() {        return this.distrito;    }
	    public void setDistrito(String distrito) {        this.distrito = distrito;    }
	   
	     @Column(name="celular", length=9)
	    public String getCelular() {        return this.celular;    }
	    
	    public void setCelular(String celular) {        this.celular = celular;    }
	 
	       @Column(name="cargo", nullable=false, length=60)
	   public String getCargo() {        return this.cargo;    }
	    
	    public void setCargo(String cargo) {        this.cargo = cargo;    }


    @Column(name="nombreCompleto", length=100)
	public String getNombreCompleto() {
		return nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}
    

//@OneToOne(fetch=FetchType.LAZY, mappedBy="empleados")
//    public Set<Usuario> getUsuarioses() {
//        return this.usuarioses;
//    }
//    
//    public void setUsuarioses(Set<Usuario> usuarioses) {
//        this.usuarioses = usuarioses;
//    }

}


