package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Horarios generated by hbm2java
 */
@Entity
@Table(name="horarios"
    ,catalog="dbcolegio2"
)
public class Horarios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short idHorario;
	private String curso;
	private String empleado;
	private String horaIni;
	private String horaFin;
	private String seccion;
	private String nroAula;
	private String dia;
	private String grado;
	private String nivelAcademico;
	private String codigoColegio;
	public Horarios() {
		
	}
	public Horarios(Short idHorario) {
		super();
		this.idHorario = idHorario;
	}
	public Horarios( String curso, String empleado,
			String horaIni, String horaFin, String seccion, String nroAula,
			String dia, String grado, String nivelAcademico,
			String codigoColegio) {
		
		this.curso = curso;
		this.empleado = empleado;
		this.horaIni = horaIni;
		this.horaFin = horaFin;
		this.seccion = seccion;
		this.nroAula = nroAula;
		this.dia = dia;
		this.grado = grado;
		this.nivelAcademico = nivelAcademico;
		this.codigoColegio = codigoColegio;
	}

	@Id @GeneratedValue(strategy=IDENTITY)
	
	
	@Column(name="IdHorario", unique=true, nullable=false)
	public Short getIdHorario() {
		return idHorario;
	}
	public void setIdHorario(Short idHorario) {
		this.idHorario = idHorario;
	}
	
	@Column(name="Curso", nullable=false, length=30)
	public String getCurso() {
		return curso;
	}
	
	
	public void setCurso(String curso) {
		this.curso = curso;
	}
	
	
	@Column(name="Empleado", nullable=false, length=100)
	public String getEmpleado() {
		return empleado;
	}
	public void setEmpleado(String empleado) {
		this.empleado = empleado;
	}
	
	@Column(name="HoraIni", nullable=false, length=10)
	public String getHoraIni() {
		return horaIni;
	}
	public void setHoraIni(String horaIni) {
		this.horaIni = horaIni;
	}
	
	@Column(name="HoraFin", nullable=false, length=10)
	public String getHoraFin() {
		return horaFin;
	}
	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}
	
	@Column(name="Seccion", nullable=false, length=10)
	public String getSeccion() {
		return seccion;
	}
	public void setSeccion(String seccion) {
		this.seccion = seccion;
	}
	
	@Column(name="nroAula", nullable=false, length=10)
	public String getNroAula() {
		return nroAula;
	}
	public void setNroAula(String nroAula) {
		this.nroAula = nroAula;
	}
	
	@Column(name="Dia", nullable=false, length=20)
	public String getDia() {
		return dia;
	}
	public void setDia(String dia) {
		this.dia = dia;
	}
	
	@Column(name="grado", nullable=false, length=10)
	public String getGrado() {
		return grado;
	}
	public void setGrado(String grado) {
		this.grado = grado;
	}
	
	@Column(name="nivelAcademico", nullable=false, length=20)
	public String getNivelAcademico() {
		return nivelAcademico;
	}
	public void setNivelAcademico(String nivelAcademico) {
		this.nivelAcademico = nivelAcademico;
	}

    @Column(name="codigoColegio", nullable=false, length=11)
	public String getCodigoColegio() {
		return codigoColegio;
	}
	public void setCodigoColegio(String codigoColegio) {
		this.codigoColegio = codigoColegio;
	}
	
}
	
	
	
	
	