package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Matriculas generated by hbm2java
 */
@Entity
@Table(name="matriculas"
    ,catalog="dbcolegio2"
)
public class Matriculas  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idMatricula;
     private Nivel nivel;
     private Alumnos alumnos;
     private String periodo;
     private Character seccion;
     private Date fecha;
     private String hora;
     private String codigoColegio;
     private Set<Pagos> pagoses = new HashSet<Pagos>(0);

    public Matriculas() {
    }

	
    public Matriculas(Nivel nivel, Alumnos alumnos, String periodo, Date fecha, String codigoColegio) {
        this.nivel = nivel;
        this.alumnos = alumnos;
        this.periodo = periodo;
        this.fecha = fecha;
        this.codigoColegio = codigoColegio;
    }
    public Matriculas(Nivel nivel, Alumnos alumnos, String periodo, Character seccion, Date fecha, String hora, String codigoColegio, Set<Pagos> pagoses) {
       this.nivel = nivel;
       this.alumnos = alumnos;
       this.periodo = periodo;
       this.seccion = seccion;
       this.fecha = fecha;
       this.hora = hora;
       this.codigoColegio = codigoColegio;
       this.pagoses = pagoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdMatricula", unique=true, nullable=false)
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdNivel", nullable=false)
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdAlumno", nullable=false)
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }

    
    @Column(name="Periodo", nullable=false, length=6)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="Seccion", length=1)
    public Character getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Character seccion) {
        this.seccion = seccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Hora", length=10)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matriculas")
    public Set<Pagos> getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set<Pagos> pagoses) {
        this.pagoses = pagoses;
    }




}


