package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Matriculas generated by hbm2java
 */
@Entity
@Table(name="matriculas"
    ,catalog="dbcolegio2"
)
public class Matriculas  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idMatricula;
     private String periodo;
     private Character seccion;
     private Date fecha;
     private String hora;
     private String codigoColegio;
     private String idAlumno;

    public Matriculas() {
    }

	
    public Matriculas(String idAlumno, String periodo, Date fecha,  Character seccion,String codigoColegio) {
       
        this.periodo = periodo;
        this.idAlumno=idAlumno;
        this.seccion = seccion;
        this.fecha = fecha;
        this.codigoColegio = codigoColegio;
    }
    public Matriculas(String idAlumno, String periodo, Character seccion, Date fecha, String hora, String codigoColegio, Set<Pagos> pagoses) {
     
       this.periodo = periodo;
       this.idAlumno=idAlumno;
       this.seccion = seccion;
       this.fecha = fecha;
       this.hora = hora;
       this.codigoColegio = codigoColegio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="IdMatricula", unique=true, nullable=false)
    public String getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(String idMatricula) {
        this.idMatricula = idMatricula;
    }

    

    @Column(name="IdAlumno", nullable=false, length=8)
   public String getIdAlumno() {
		return idAlumno;
	}

	public void setIdAlumno(String idAlumno) {
		this.idAlumno = idAlumno;
	}

	     
    @Column(name="Periodo", nullable=false, length=6)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="Seccion", length=1)
    public Character getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Character seccion) {
        this.seccion = seccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Hora", length=10)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="codigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }




}


