package com.juancarlos.sismat.dominio;

//Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name = "matriculacurso", catalog = "dbcolegio2")
public class MatriculaCurso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idMatriculaCurso;
	private String idCurso;
	private Integer idMatricula;
	private String tipo;
	private String motivo;
	private String codigoColegio;

	public MatriculaCurso() {
	}

	public MatriculaCurso(Integer idMatriculaCurso) {
		super();
		this.idMatriculaCurso = idMatriculaCurso;
	}

	public MatriculaCurso(String idCurso, Integer idMatricula, String tipo,
			String motivo, String codigoColegio) {
		super();
		this.idCurso = idCurso;
		this.idMatricula = idMatricula;
		this.tipo = tipo;
		this.motivo = motivo;
		this.codigoColegio = codigoColegio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdMatriculaCurso", unique = true, nullable = false)
	public Integer getIdMatriculaCurso() {
		return idMatriculaCurso;
	}

	public void setIdMatriculaCurso(Integer idMatriculaCurso) {
		this.idMatriculaCurso = idMatriculaCurso;
	}

	@Column(name = "idCurso", nullable = false, length = 5)
	public String getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(String idCurso) {
		this.idCurso = idCurso;
	}

	@Column(name = "IdMatricula", nullable = false, length = 5)
	public Integer getIdMatricula() {
		return idMatricula;
	}

	public void setIdMatricula(Integer idMatricula) {
		this.idMatricula = idMatricula;
	}

	@Column(name = "Tipo", nullable = false, length = 20)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "Motivo", nullable = false, length = 20)
	public String getMotivo() {
		return motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "codigoColegio", nullable = false, length = 11)
	public String getCodigoColegio() {
		return this.codigoColegio;
	}

	public void setCodigoColegio(String codigoColegio) {
		this.codigoColegio = codigoColegio;
	}

}
