package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table(name="nivel"
    ,catalog="dbcolegio2"
)
public class Nivel  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idNivel;
     private String tipo;
     private String nivelAcademico;
     private String orden;
     private String nroVacantes;
     private char estado;
     private String codigoColegio;
     private String nivel;
    public Nivel() {
    }

	
    public Nivel(String tipo,String nivelAcademico,String nivel, String orden, String nroVacantes, char estado) {
    	this.tipo=tipo;
        this.nivelAcademico = nivelAcademico;
        this.orden = orden;
        this.nroVacantes = nroVacantes;
        this.estado = estado;
        this.nivel=nivel;
    }
 
   
     public Nivel(Integer idNivel, String tipo, String nivelAcademico, String nivel,String orden,String codigoColegio,
			String nroVacantes, char estado) {
		super();
		this.idNivel = idNivel;
		this.tipo = tipo;
		this.nivelAcademico = nivelAcademico;
		this.orden = orden;
		this.nroVacantes = nroVacantes;
		this.estado = estado;
		this.codigoColegio = codigoColegio;
		this.nivel=nivel;
	}


	@Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="IdNivel", unique=true, nullable=false)
    public Integer getIdNivel() {
        return this.idNivel;
    }
    
    public void setIdNivel(Integer idNivel) {
        this.idNivel = idNivel;
    }


    
    @Column(name="nivelAcademico", nullable=false, length=60)
    public String getNivelAcademico() {
        return this.nivelAcademico;
    }
    
    public void setNivelAcademico(String nivelAcademico) {
        this.nivelAcademico = nivelAcademico;
    }

    
    @Column(name="Orden", nullable=false, length=10)
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }

    
    @Column(name="NroVacantes", nullable=false, length=6)
    public String getNroVacantes() {
        return this.nroVacantes;
    }
    
    public void setNroVacantes(String nroVacantes) {
        this.nroVacantes = nroVacantes;
    }

    
    @Column(name="Estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    
    @Column(name="Tipo", nullable=false, length=10)

    public String getTipo() {
		return tipo;
	}


	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

    
    
    @Column(name="codigoColegio", nullable=false, length=11)
   public String getCodigoColegio() {
      return this.codigoColegio;
   }
    

public void setCodigoColegio(String codigoColegio) {
      this.codigoColegio = codigoColegio;
 }

@Column(name="nivel", nullable=false, length=60)
public String getNivel() {
	return nivel;
}


public void setNivel(String nivel) {
	this.nivel = nivel;
}




}


