package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name="pagos"
    ,catalog="dbcolegio2"
)
public class Pagos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPago;
     private Matriculas matriculas;
     private Date fecha;
     private String hora;
     private BigDecimal total;
     private String codigoColegio;

    public Pagos() {
    }

    public Pagos(Matriculas matriculas, Date fecha, String hora, BigDecimal total, String codigoColegio) {
       this.matriculas = matriculas;
       this.fecha = fecha;
       this.hora = hora;
       this.total = total;
       this.codigoColegio = codigoColegio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdPago", unique=true, nullable=false)
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdMatricula", nullable=false)
    public Matriculas getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Matriculas matriculas) {
        this.matriculas = matriculas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Hora", nullable=false, length=10)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }

    
    @Column(name="Total", nullable=false, precision=6)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }




}


