package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name="seccion"
    ,catalog="dbcolegio2"
)
public class Seccion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short idSeccion;
     private String idEmpleado;
     private String grado;
     private String nivelAcademico;
     private String seccion;
     private String nroVacantes;
     private String nroAula;
     private String periodo;
     private String codigoColegio;

    public Seccion() {
    }

	
    public Seccion(Short idSeccion) {
		super();
		this.idSeccion = idSeccion;
	}

   
     public Seccion(Short idSeccion, String idEmpleado, String grado,
			String nivelAcademico, String seccion, String nroVacantes,
			String nroAula, String periodo,String codigoColegio) {
		super();
		this.idSeccion = idSeccion;
		this.idEmpleado = idEmpleado;
		this.grado = grado;
		this.nivelAcademico = nivelAcademico;
		this.seccion = seccion;
		this.nroVacantes = nroVacantes;
		this.nroAula = nroAula;
		this.periodo = periodo;
		this.codigoColegio=codigoColegio;
	}


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSeccion", unique=true, nullable=false)
    public Short getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Short idSeccion) {
        this.idSeccion = idSeccion;
    }

   
    @Column(name="idEmpleado", nullable=false, length=8)
	public String getIdEmpleado() {
		return idEmpleado;
	}


	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

    @Column(name="grado", nullable=false, length=20)
	public String getGrado() {
		return grado;
	}


	public void setGrado(String grado) {
		this.grado = grado;
	}

    @Column(name="nivelAcademico", nullable=false, length=50)
	public String getNivelAcademico() {
		return nivelAcademico;
	}


	public void setNivelAcademico(String nivelAcademico) {
		this.nivelAcademico = nivelAcademico;
	}

    @Column(name="seccion", nullable=false, length=2)
	public String getSeccion() {
		return seccion;
	}


	public void setSeccion(String seccion) {
		this.seccion = seccion;
	}

    @Column(name="nroVacantes", nullable=false, length=3)
	public String getNroVacantes() {
		return nroVacantes;
	}


	public void setNroVacantes(String nroVacantes) {
		this.nroVacantes = nroVacantes;
	}

    @Column(name="nroAula", nullable=false, length=3)
	public String getNroAula() {
		return nroAula;
	}


	public void setNroAula(String nroAula) {
		this.nroAula = nroAula;
	}

    @Column(name="periodo", nullable=false, length=4)
	public String getPeriodo() {
		return periodo;
	}


	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}
    


    

    
    @Column(name="codigoColegio", nullable=false, length=11)
  public String getCodigoColegio() {
    return this.codigoColegio;
  }
    
 public void setCodigoColegio(String codigoColegio) {
   this.codigoColegio = codigoColegio;
 }






}


