package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name="cursos"
    ,catalog="dbcolegio2"
)
public class Cursos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Short idCurso;
     private String nombre;
     private String grado;
     private String nivelAcademico;
     private String area;
     private char estado;
    // private String codigoColegio;
     private Set<Horarios> horarioses = new HashSet<Horarios>(0);

    public Cursos() {
    }

	
    public Cursos(Short idCurso) {
		super();
		this.idCurso = idCurso;
	}


	
    public Cursos(String nombre, String grado,
			String nivelAcademico, String area, char estado) {
		super();
		this.nombre = nombre;
		this.grado = grado;
		this.nivelAcademico = nivelAcademico;
		this.area = area;
		this.estado = estado;
	}


	public Cursos(String nombre, char estado, Set<Horarios> horarioses) {
       this.nombre = nombre;
       this.estado = estado;
     //  this.codigoColegio = codigoColegio;
       this.horarioses = horarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCurso", unique=true, nullable=false)
    public Short getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Short idCurso) {
        this.idCurso = idCurso;
    }

    
    @Column(name="Nombre", nullable=false, length=70)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    

    
 //   @Column(name="CodigoColegio", nullable=false, length=11)
   // public String getCodigoColegio() {
     //   return this.codigoColegio;
   // }
    
    //public void setCodigoColegio(String codigoColegio) {
      //  this.codigoColegio = codigoColegio;
    //}

    
    @Column(name="Grado", nullable=false, length=50)
    public String getGrado() {
		return grado;
	}


	public void setGrado(String grado) {
		this.grado = grado;
	}

	@Column(name="NivelAcademico", nullable=false, length=50)
	public String getNivelAcademico() {
		return nivelAcademico;
	}


	public void setNivelAcademico(String nivelAcademico) {
		this.nivelAcademico = nivelAcademico;
	}

	@Column(name="Area", nullable=false, length=50)
	public String getArea() {
		return area;
	}


	public void setArea(String area) {
		this.area = area;
	}

    @Column(name="Estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cursos")
    public Set<Horarios> getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set<Horarios> horarioses) {
        this.horarioses = horarioses;
    }




}


