package com.juancarlos.sismat.dominio;
// Generated 20-abr-2015 23:35:22 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Horarios generated by hbm2java
 */
@Entity
@Table(name="horarios"
    ,catalog="dbcolegio2"
)
public class Horarios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHorario;
     private Empleado empleado;
     private Cursos cursos;
     private Nivel nivel;
     private String dia;
     private String horaIni;
     private String horaFin;
     private String codigoColegio;

    public Horarios() {
    }

    public Horarios(Empleado empleado, Cursos cursos, Nivel nivel, String dia, String horaIni, String horaFin, String codigoColegio) {
       this.empleado = empleado;
       this.cursos = cursos;
       this.nivel = nivel;
       this.dia = dia;
       this.horaIni = horaIni;
       this.horaFin = horaFin;
       this.codigoColegio = codigoColegio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdHorario", unique=true, nullable=false)
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Profesor", nullable=false)
    public Empleado getEmpleados() {
        return this.empleado;
    }
    
    public void setEmpleados(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCurso", nullable=false)
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdNivel", nullable=false)
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="Dia", nullable=false, length=20)
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }

    
    @Column(name="HoraIni", nullable=false, length=10)
    public String getHoraIni() {
        return this.horaIni;
    }
    
    public void setHoraIni(String horaIni) {
        this.horaIni = horaIni;
    }

    
    @Column(name="HoraFin", nullable=false, length=10)
    public String getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }

    
    @Column(name="CodigoColegio", nullable=false, length=11)
    public String getCodigoColegio() {
        return this.codigoColegio;
    }
    
    public void setCodigoColegio(String codigoColegio) {
        this.codigoColegio = codigoColegio;
    }




}


